# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bbdb2a5dcaa630e888182fc7c6f7681c2c48d91cf75b0a9ebc93e304838e77354fe2b25064fea2fffc9126aed5eb44ba9fc56e073aa9acd85ea13d4c9aeeb446

test:
  secret_key_base: b5eed81e69f527daa1c6842099e8ca2e4547b391ca23500dce4bbec3ce14cd08794181031e9135fd21a9f8d88af5ccc32174d0351ca03230d29b74bd9b82422c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
